local harpoon = require("harpoon")

harpoon:setup({})

vim.keymap.set("n", "<C-e>", function()
	harpoon.ui:toggle_quick_menu(harpoon:list())
end, { desc = "Open Harpoon window" })
vim.keymap.set("n", "<leader>ha", function()
	harpoon:list():append()
end, { desc = "<h>arpoon <a>dd buffer to list" })

vim.keymap.set("n", "<leader>1", function()
	harpoon:list():select(1)
end, { desc = "Go to item 1 of the list" })
vim.keymap.set("n", "<leader>2", function()
	harpoon:list():select(2)
end, { desc = "Go to item 2 of the list" })
vim.keymap.set("n", "<leader>3", function()
	harpoon:list():select(3)
end, { desc = "Go to item 3 of the list" })
vim.keymap.set("n", "<leader>4", function()
	harpoon:list():select(4)
end, { desc = "Go to item 4 of the list" })
