#!/bin/zsh

update_git_branch() {
	if git rev-parse --is-inside-work-tree &>/dev/null; then
		CURRENT_GIT_BRANCH=$(git branch --show-current 2>/dev/null)

		if [[ -z "$CURRENT_GIT_BRANCH" ]]; then
			CURRENT_GIT_BRANCH=$(git rev-parse --short HEAD 2>/dev/null)
			if [[ -n "$CURRENT_GIT_BRANCH" ]]; then
				CURRENT_GIT_BRANCH="(detached $CURRENT_GIT_BRANCH)"
			fi
		fi

		export CURRENT_GIT_BRANCH
	else
		unset CURRENT_GIT_BRANCH
	fi
}

precmd_functions+=(update_git_branch)

update_git_branch
